### ISSUE TITLE
Fallout ScanMsg binary exe

### ISSUE THREAD

**Issue by ghostlyghastly** [wipe2238/ScanMsg#4]
This is freaking useful, thank you. Nevada's EN translation has one double ID error turns out. Sonora's RU is clean.
 A binary would be great! Here's one for desperate noncompilers out there:
[ScanMsg.zip](https://github.com/wipe2238/ScanMsg/files/10892153/ScanMsg.zip)

**Comment by wipe2238** [comment]
I know it's many months late (shame, shame on me...), but most recent binaries are always available in 1@2 repo

https://github.com/rotators/Fo1in2/tree/master/Tools/ScanMsg/

It's synched daily with this repo, so at the moment it's **the** place for binaries.

---

If using GitHub Actions, you don't really need executables, as you can easily run ScanMsg whenever .msg file(s) changes. Here's how we do it in 1@2:

```yaml
name: Text

on:
 push:
  paths:
  - '.github/workflows/text.yml'
  - 'Fallout2/Fallout1in2/**/*.[Mm][Ss][Gg]'
 pull_request:
  paths:
  - '.github/workflows/text.yml'
  - 'Fallout2/Fallout1in2/**/*.[Mm][Ss][Gg]'

defaults:
 run:
  shell: bash

jobs:
 ScanMsg:
  runs-on: windows-latest
  steps:

  - name: Clone
    uses: actions/checkout@v3

  - name: ScanMsg
    uses: wipe2238/ScanMsg@master
    with:
     workdir: Fallout2/Fallout1in2/mods/
```

Additional `with` arguments can be found [here](https://github.com/wipe2238/ScanMsg/blob/master/action.yml). If used from private repo, it's probably good idea to change `runs-on` to `ubuntu-latest` due to [minute multipliers](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#minute-multipliers).

---

Main reason why i didn't bother with permanent artifacts (there are temporary ones, kept for 30d after each commit) is a fact that at the time only two projects used it, and same person handled both. Now, over two years later, i have no  clue who might be using it, but they already found binaries one way or another ;)

Unless there will be actual code changes (doubtful, there's not really anything to add i can think of), 1@2 will stop keeping .exe around, or i'll get into messing with GitHub Actions again, i'm going to keep this for anyone interested in binaries.
